### ISSUE TITLE
Livecoding.tv TODO list

### ISSUE THREAD

**Issue by noisy** [noisy/piston-web#1]
- [x] - checkout latest dev branch
- [ ] - setup Steem node
- [x] - investigate differences between `python steem` and `piston`
- [x] - implement `list_accounts` generator
  - [x] - why `-1` is a legal argument for `lookup_accounts(const string& lower_bound_name, uint32_t limit)const;` - [src](https://github.com/steemit/steem/blob/045c2a340d254d11dfcd22e1253646132465f9b7/libraries/app/include/steemit/app/database_api.hpp#L190)

 
  
 
 
 

.
